
	Running main.py

IMPORT DONE.

	 Reading benign_traffic...##

	 Reading Ack Attack...##

Read SucessFull.


***Number of Benign before balance.
benign SHape: (555932, 115)

***Number of Attack before balance.
attack SHape: (643821, 115)
Number of Benign After balance.
benign SHape: (555932, 115)
Number of Attack After balance.
attack SHape: (556032, 115)
COMBINED SHape: (1111964, 116)
After remove: (1111964, 114)
The OUTPUt is : [0 0 0 ... 1 1 0]
COMBINED SHape: (1111964,)
Output SHape: (1111964, 30)

************Attck 1 (Ack) ***************** 

	Running DecisionTreeRegressor . . . 
Accuracy Score First MODEL is : 1.0
	Running GaussianNB . . . 

Accuracy Score Second MODEL is : 0.9659821937108426
	Running RandomForestClassifier . . . 

Accuracy Score Third MODEL is : 1.0

>>>>>>>>>>>Selected model : RandomForestClassifier
>>>>>>>>>>>>>>>>Accuracy Value : 1.0
